# Generated by Django 2.0.5 on 2019-01-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=1000)),
                ('Password', models.CharField(max_length=1000)),
            ],
        ),
    ]
