# Generated by Django 2.0.5 on 2019-01-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_auto_20190111_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
