# Generated by Django 2.0.5 on 2019-01-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0007_auto_20190111_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
