# Generated by Django 2.1.5 on 2019-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0009_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=0, max_length=1000000),
            preserve_default=False,
        ),
    ]
