# Generated by Django 2.1.5 on 2019-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0010_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
